### ISSUE TITLE
DeprecationWarning: using version 9.0.0

### ISSUE THREAD

**Issue by shlomogcap** [jaydenseric/extract-files#30]
(node:13559) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./public/" in the "exports" field module resolution of the package at PROJECT_DIR/node_modules/extract-files/package.json.
Update this package.json to use a subpath pattern like "./public/*".
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by jaydenseric** [comment]
Sorry for the late response; for some reason I missed the notification for this issue.

Duplicates https://github.com/jaydenseric/extract-files/issues/17 .

This issue was fixed in [v10.0.0](https://github.com/jaydenseric/extract-files/releases/tag/v10.0.0) by https://github.com/jaydenseric/extract-files/commit/e2f11e06e1c3c0cc0f1329468ac90326e405f9d9 .
