### ISSUE TITLE
Does not work with webpack v3.8.1

### ISSUE THREAD

**Issue by bora89** [jaydenseric/extract-files#6]
Planned to use your Apollo GraphQL Link thing, but it depends on this lib, and webpack v3.8.1, loads index.mjs and does not understand what to do with it. Probably will have to implement a legacy file upload...

**Comment by taviroquai** [comment]
Changing the "module" param in the package.json:
"module": "lib/index.js"
...seems to work. I suppose index.js is the compiled ES5 version of the index.mjs...

**Comment by bora89** [comment]
Thanks @taviroquai! I spent toooo much time on it, so I gave up with apollo-upload. Implemented a "standard" express file upload, a way more robust.

**Comment by taviroquai** [comment]
@bora89 hey. Me too, I'm using AdonisJS for file-upload. I dig down the hole and went to busboy.parse() but somehow the parse doesn't trigger the field and file events...

**Comment by bora89** [comment]
I use the multer on server side - quite flexible. It is written on top of busboy. Have a try! And for client uploader - Antd Upload

**Comment by jaydenseric** [comment]
@bora89 I'm not sure why you are having issues, Webpack is working fine in (apollo-upload-examples)[https://github.com/jaydenseric/apollo-upload-examples] via Next.js.

Going back on `.mjs` is non-negotiable, it is the official way to use native ESM in Node.js. `extract-files` is also dependency of [`graphql-react`](https://github.com/jaydenseric/graphql-react), which fully supports native ESM.

Some packages such as Webpack, CRA and Apollo have had teething issues adapting to the new paradigm. In webpack v4, `.mjs` is a first-class citizen and resolves before `.js`. I suggest upgrading as soon as you can as v3 had a few bugs.

If you're absolutely blocked and want to implement your own client solution, I advise conforming to the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec) for interoperability with existing server solutions, to avoid fragmenting the comunity and to simply save yourself a lot of time.

We can reopen this if you provide reproduction steps that demonstrate a specific issue with this package and not something that should be fixed in Apollo or Webpack 😌
